"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and , the first terms will be: 

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci_sum(num):
    a = 0
    b = 1
    ans = 0
    while a < num:
        a = b
        b = a + b
        if b % 2 == 0:
            ans = ans + b
return ans
