"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms 10 will be: 
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Source: EulerProject
"""

def fibonacci_sum(num):
    a = 0
    b = 1
    ans = 0
    while a < num:
        a = b
        b = a + b
        if b % 2 == 0:
            ans = ans + b
return ans

def fib_generator(num):
    if num == 0:
        return []
    else:
        result = [1, 2]
        for i in range(2, n):
            result.append(result[-1] + result[-2])
        return result
        
